version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
      -  POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50001:50000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    restart: always
    networks:
      - net_jenkins
volumes:
  jenkins_home:
networks:
  postgres-compose-network:
    driver: bridge
  net_jenkins: